# Generated by Django 4.0.1 on 2022-01-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employee_password_remove_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='lname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
