# Generated by Django 4.0.1 on 2022-01-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_fname_employee_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lname',
        ),
    ]
