# Generated by Django 4.0.1 on 2022-02-08 13:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_fname_employee_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='photo.jpg', upload_to=accounts.models.image_upload),
        ),
    ]
