# Generated by Django 4.0.1 on 2022-01-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_locx_order_locy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receive',
            field=models.IntegerField(default=1),
        ),
    ]
