# Generated by Django 4.0.1 on 2022-01-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
