# Generated by Django 4.0.1 on 2022-01-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='done',
            field=models.IntegerField(default=0),
        ),
    ]
