# Generated by Django 4.0.1 on 2022-02-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_description2'),
        ('order', '0007_alter_order_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_products',
            field=models.IntegerField(default=4),
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
