# Generated by Django 4.0.1 on 2022-02-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_products_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
