# Generated by Django 4.0.1 on 2022-01-13 14:57

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to=products.models.image_upload)),
            ],
        ),
    ]
