# Generated by Django 4.0.1 on 2022-01-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='hide',
            field=models.IntegerField(default=2),
        ),
    ]
