# Generated by Django 4.0.1 on 2022-01-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description2',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
