# Generated by Django 4.0.1 on 2022-01-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_description2_products_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
