# Generated by Django 4.0.1 on 2022-02-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
